---
name: Test-Scenario
author: Arne Tarara
version: 1
architecture: linux

services:
  Single_load_Container:
    image: quoinedev/python3.7-pandas-alpine
    ports:
      - 9001:80
    setup-commands:
      - command: python3 -m pip install pandas

flow:
  - name: Load 10000000
    container: Single_load_Container
    commands:
      - type: console
        command: python3 /tmp/repo/test_load_hash.py run -n 100000
        note: Running ML Code with mini load 100000
  - name: Cleanup single load
    container: Single_load_Container
    commands:
      - type: console
        command: python3 /tmp/repo/test_load_hash.py cleanup
        note: Doing Cleanup on Single_load_Container
