---
name: Test-Scenario
author: Arne Tarara
version: 1
description: Defined test scenario for used in Green Coding Berlin automated tests.

services:
  Small_load_Container:
    image: quoinedev/python3.7-pandas-alpine
    ports:
      - 9000:80
    setup-commands:
      - command: whoami
      - command: python3 -m pip install pandas
  High_load_Container:
    image: quoinedev/python3.7-pandas-alpine
    ports:
      - 9001:80
    setup-commands:
      - command: python3 -m pip install pandas

flow:
  - name: Load 1000
    container: Small_load_Container
    commands:
      - type: console
        command: python3 /tmp/repo/test_load_hash.py run -n 10000000
        detach: true
        note: Running ML Code with 10000000 detached
  - name: Load 10000000
    container: High_load_Container
    commands:
      - type: console
        command: python3 /tmp/repo/test_load_hash.py run -n 100000000
        note: Running ML Code with 100000000 sync
  - name: Cleanup small load
    container: Small_load_Container
    commands:
      - type: console
        command: python3 /tmp/repo/test_load_hash.py cleanup
        note: Doing Cleanup on Small_load_Container
  - name: Cleanup high load
    container: High_load_Container
    commands:
      - type: console
        command: python3 /tmp/repo/test_load_hash.py cleanup
        note: Doing Cleanup on High_load_Container
